name: 'GitHub Actions Youthstudy Bot'
# UTC17:00(北京UTC+8 01:00点)触发任务
on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  youthstudymark:
    runs-on: ubuntu-latest
    steps:
      - name: checkout actions
        uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Add xLitemallToken to python file
        run: |
          sed -i '1i\xLitemallToken="${{ secrets.xLitemallToken }}"' main.py
          echo "​pushdata = '{"token":"${{ secrets.pushtoken }}","title":"'+name+json​.​loads​(​saveHistory​.​text​).​get​(​'msg'​)+'","content":"'+"更新日期:"​+updateDate​,+"名称:"​+name​+"打卡状态:"​+json​.​loads​(​saveHistory​.​text​).​get​(​'msg'​)+'","topic":"test"}'" > main.py
          echo "​mark​ ​=​ ​requests​.​post(​'http://www.pushplus.plus/send/',data = pushdata)" > main.py
      
      - name: Set up env
        run: pip install -r requirement.txt
          
      - name: command
        run: |
          python main.py
